### ISSUE TITLE
Kaas 1.0.5 , Adding models resets current session settings

### ISSUE THREAD

**Issue by tosho** [0xfrankz/Kaas#2]
That was a very quick update!

The previous issue with the settings is no more but now during your session if you change something in the Settings and if you go and add a new model from the Models menu the new settings for the session will reset. You need to restart the application after doing Settings then add new models.

The fixed position of the sidebar gets back to hide when the app is restarted.

Feature requests: 
- adding settings per model on the models new/edit menu.
- ability to export chats
- quick light/dark mode button in the front rather going to Settings (IMO maybe new themes, the white and yellow font don't look good, also maybe lighter Dark theme)
- UI scale or Changing Font Size would be nice

P.S.
Where are the sessions/chats and images stored? I can't find it in the installation folder neither in $user/.AppData

P.S. 2 :
the width of the chat is quite tight. Copying text (with selection of a paragraph or whatever) copies to whole answer. And if you try to copy some code it gets messy. Copy button on generated code would be nice.

using Win 10 x64

**Comment by 0xfrankz** [comment]
Thanks for the feedback! I'm looking into these issues.

The chat data is store in a SQLite file in $user\AppData\Roaming\kassapp.com; all images is stored in the "cache" subfolder.
Will add functions to manage data & cache storage soon.

**Comment by 0xfrankz** [comment]
Hi tosho, just released v1.0.6 and fixed some issues you mentioned:

1. Fixed the bug where some settings are reset after adding/editing models
2. The "pinned" status of the side bar is now remebered after closing the app
3. Added a button to copy code blocks in bot's messages
4. You can know adjust the layout of the chat section, two widths are available now: 640px and 800 px

The rest of the feature requests are on my list, will roll out in the following releases.

As for new themes, I'm afraid it has to wait till I find a professional designer on board.

Let me know if you have more ideas/suggestions.

FZ
