### ISSUE TITLE
Wen Tauri v2? 

### ISSUE THREAD

**Issue by slavakurilyak** [0xfrankz/Kaas#8]
It would be great to see this project use [Tauri v2](https://v2.tauri.app/blog/tauri-20/)

**Comment by 0xfrankz** [comment]
Soon, love some of the interesting capabilities provided by v2. Just want to finish some features first that are under development right now.

**Comment by 0xfrankz** [comment]
Hi Slava, just upgraded Tauri to v2, you can try v1.0.7 out.

Mind if ask which functions of Tauri v2 are you insterested in?
